/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData cog = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_cw = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xf006, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_ext = IconData(0xf08e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docs = IconData(0xf0c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
